/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as ForTradesmenRouteImport } from './routes/for-tradesmen'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as ProIdRouteImport } from './routes/pro.$id'
import { Route as TradesIndexRouteImport } from './routes/trades.index'
import { Route as TradesTradeRouteImport } from './routes/trades.$trade'
import { Route as WaitingListIndexRouteImport } from './routes/waiting-list.index'
import { Route as WaitingListThanksRouteImport } from './routes/waiting-list.thanks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const ForTradesmenRoute = ForTradesmenRouteImport.update({
  id: '/for-tradesmen',
  path: '/for-tradesmen',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIdRoute = ProIdRouteImport.update({
  id: '/pro/$id',
  path: '/pro/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesIndexRoute = TradesIndexRouteImport.update({
  id: '/trades/',
  path: '/trades/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesTradeRoute = TradesTradeRouteImport.update({
  id: '/trades/$trade',
  path: '/trades/$trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingListIndexRoute = WaitingListIndexRouteImport.update({
  id: '/waiting-list/',
  path: '/waiting-list/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingListThanksRoute = WaitingListThanksRouteImport.update({
  id: '/waiting-list/thanks',
  path: '/waiting-list/thanks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/areas': typeof AreasRoute
  '/claim': typeof ClaimRoute
  '/enterprise': typeof EnterpriseRoute
  '/for-tradesmen': typeof ForTradesmenRoute
  '/post-job': typeof PostJobRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/admin/plans': typeof AdminPlansRoute
  '/pro/$id': typeof ProIdRoute
  '/trades/$trade': typeof TradesTradeRoute
  '/waiting-list/thanks': typeof WaitingListThanksRoute
  '/trades/': typeof TradesIndexRoute
  '/waiting-list/': typeof WaitingListIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/areas': typeof AreasRoute
  '/claim': typeof ClaimRoute
  '/enterprise': typeof EnterpriseRoute
  '/for-tradesmen': typeof ForTradesmenRoute
  '/post-job': typeof PostJobRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/admin/plans': typeof AdminPlansRoute
  '/pro/$id': typeof ProIdRoute
  '/trades/$trade': typeof TradesTradeRoute
  '/waiting-list/thanks': typeof WaitingListThanksRoute
  '/trades': typeof TradesIndexRoute
  '/waiting-list': typeof WaitingListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/areas': typeof AreasRoute
  '/claim': typeof ClaimRoute
  '/enterprise': typeof EnterpriseRoute
  '/for-tradesmen': typeof ForTradesmenRoute
  '/post-job': typeof PostJobRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/admin/plans': typeof AdminPlansRoute
  '/pro/$id': typeof ProIdRoute
  '/trades/$trade': typeof TradesTradeRoute
  '/waiting-list/thanks': typeof WaitingListThanksRoute
  '/trades/': typeof TradesIndexRoute
  '/waiting-list/': typeof WaitingListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/areas'
    | '/claim'
    | '/enterprise'
    | '/for-tradesmen'
    | '/post-job'
    | '/privacy'
    | '/signin'
    | '/sitemap.xml'
    | '/terms'
    | '/verification'
    | '/admin/plans'
    | '/pro/$id'
    | '/trades/$trade'
    | '/waiting-list/thanks'
    | '/trades/'
    | '/waiting-list/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/areas'
    | '/claim'
    | '/enterprise'
    | '/for-tradesmen'
    | '/post-job'
    | '/privacy'
    | '/signin'
    | '/sitemap.xml'
    | '/terms'
    | '/verification'
    | '/admin/plans'
    | '/pro/$id'
    | '/trades/$trade'
    | '/waiting-list/thanks'
    | '/trades'
    | '/waiting-list'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/areas'
    | '/claim'
    | '/enterprise'
    | '/for-tradesmen'
    | '/post-job'
    | '/privacy'
    | '/signin'
    | '/sitemap.xml'
    | '/terms'
    | '/verification'
    | '/admin/plans'
    | '/pro/$id'
    | '/trades/$trade'
    | '/waiting-list/thanks'
    | '/trades/'
    | '/waiting-list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AreasRoute: typeof AreasRoute
  ClaimRoute: typeof ClaimRoute
  EnterpriseRoute: typeof EnterpriseRoute
  ForTradesmenRoute: typeof ForTradesmenRoute
  PostJobRoute: typeof PostJobRoute
  PrivacyRoute: typeof PrivacyRoute
  SigninRoute: typeof SigninRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VerificationRoute: typeof VerificationRoute
  AdminPlansRoute: typeof AdminPlansRoute
  ProIdRoute: typeof ProIdRoute
  TradesTradeRoute: typeof TradesTradeRoute
  WaitingListThanksRoute: typeof WaitingListThanksRoute
  TradesIndexRoute: typeof TradesIndexRoute
  WaitingListIndexRoute: typeof WaitingListIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-tradesmen': {
      id: '/for-tradesmen'
      path: '/for-tradesmen'
      fullPath: '/for-tradesmen'
      preLoaderRoute: typeof ForTradesmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/$id': {
      id: '/pro/$id'
      path: '/pro/$id'
      fullPath: '/pro/$id'
      preLoaderRoute: typeof ProIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/': {
      id: '/trades/'
      path: '/trades'
      fullPath: '/trades/'
      preLoaderRoute: typeof TradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/$trade': {
      id: '/trades/$trade'
      path: '/trades/$trade'
      fullPath: '/trades/$trade'
      preLoaderRoute: typeof TradesTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting-list/': {
      id: '/waiting-list/'
      path: '/waiting-list'
      fullPath: '/waiting-list/'
      preLoaderRoute: typeof WaitingListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting-list/thanks': {
      id: '/waiting-list/thanks'
      path: '/waiting-list/thanks'
      fullPath: '/waiting-list/thanks'
      preLoaderRoute: typeof WaitingListThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AreasRoute: AreasRoute,
  ClaimRoute: ClaimRoute,
  EnterpriseRoute: EnterpriseRoute,
  ForTradesmenRoute: ForTradesmenRoute,
  PostJobRoute: PostJobRoute,
  PrivacyRoute: PrivacyRoute,
  SigninRoute: SigninRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VerificationRoute: VerificationRoute,
  AdminPlansRoute: AdminPlansRoute,
  ProIdRoute: ProIdRoute,
  TradesTradeRoute: TradesTradeRoute,
  WaitingListThanksRoute: WaitingListThanksRoute,
  TradesIndexRoute: TradesIndexRoute,
  WaitingListIndexRoute: WaitingListIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
