/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as ForTradesmenRouteImport } from './routes/for-tradesmen'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProIdRouteImport } from './routes/pro.$id'
import { Route as TradesIndexRouteImport } from './routes/trades.index'
import { Route as TradesTradeRouteImport } from './routes/trades.$trade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ForTradesmenRoute = ForTradesmenRouteImport.update({
  id: '/for-tradesmen',
  path: '/for-tradesmen',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIdRoute = ProIdRouteImport.update({
  id: '/pro/$id',
  path: '/pro/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesIndexRoute = TradesIndexRouteImport.update({
  id: '/trades/',
  path: '/trades/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesTradeRoute = TradesTradeRouteImport.update({
  id: '/trades/$trade',
  path: '/trades/$trade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/areas': typeof AreasRoute
  '/for-tradesmen': typeof ForTradesmenRoute
  '/post-job': typeof PostJobRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/pro/$id': typeof ProIdRoute
  '/trades/$trade': typeof TradesTradeRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/areas': typeof AreasRoute
  '/for-tradesmen': typeof ForTradesmenRoute
  '/post-job': typeof PostJobRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/pro/$id': typeof ProIdRoute
  '/trades/$trade': typeof TradesTradeRoute
  '/trades': typeof TradesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/areas': typeof AreasRoute
  '/for-tradesmen': typeof ForTradesmenRoute
  '/post-job': typeof PostJobRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/pro/$id': typeof ProIdRoute
  '/trades/$trade': typeof TradesTradeRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/areas'
    | '/for-tradesmen'
    | '/post-job'
    | '/privacy'
    | '/signin'
    | '/terms'
    | '/pro/$id'
    | '/trades/$trade'
    | '/trades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/areas'
    | '/for-tradesmen'
    | '/post-job'
    | '/privacy'
    | '/signin'
    | '/terms'
    | '/pro/$id'
    | '/trades/$trade'
    | '/trades'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/areas'
    | '/for-tradesmen'
    | '/post-job'
    | '/privacy'
    | '/signin'
    | '/terms'
    | '/pro/$id'
    | '/trades/$trade'
    | '/trades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AreasRoute: typeof AreasRoute
  ForTradesmenRoute: typeof ForTradesmenRoute
  PostJobRoute: typeof PostJobRoute
  PrivacyRoute: typeof PrivacyRoute
  SigninRoute: typeof SigninRoute
  TermsRoute: typeof TermsRoute
  ProIdRoute: typeof ProIdRoute
  TradesTradeRoute: typeof TradesTradeRoute
  TradesIndexRoute: typeof TradesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-tradesmen': {
      id: '/for-tradesmen'
      path: '/for-tradesmen'
      fullPath: '/for-tradesmen'
      preLoaderRoute: typeof ForTradesmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/$id': {
      id: '/pro/$id'
      path: '/pro/$id'
      fullPath: '/pro/$id'
      preLoaderRoute: typeof ProIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/': {
      id: '/trades/'
      path: '/trades'
      fullPath: '/trades/'
      preLoaderRoute: typeof TradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/$trade': {
      id: '/trades/$trade'
      path: '/trades/$trade'
      fullPath: '/trades/$trade'
      preLoaderRoute: typeof TradesTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AreasRoute: AreasRoute,
  ForTradesmenRoute: ForTradesmenRoute,
  PostJobRoute: PostJobRoute,
  PrivacyRoute: PrivacyRoute,
  SigninRoute: SigninRoute,
  TermsRoute: TermsRoute,
  ProIdRoute: ProIdRoute,
  TradesTradeRoute: TradesTradeRoute,
  TradesIndexRoute: TradesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
