INSERT INTO public.trades (slug, name, blurb, typical_cost, sort_order) VALUES
('bathroom-fitter','Bathroom Fitter','Full bathroom installs, wet rooms, showers and en-suites.','£1,500 – £9,000',1),
('blacksmith','Blacksmith / Metal Worker','Gates, railings, balustrades and bespoke metalwork.','£200 – £8,000',2),
('bricklayer','Bricklayer','Walls, extensions, repointing and brick repairs.','£300 – £15,000',3),
('builder','Builder','Extensions, structural work, conversions and full renovations.','£1,800 – £45,000',4),
('carpenter','Carpenter / Joiner','Fitted joinery, doors, staircases, decking and second fix.','£200 – £8,000',5),
('cctv-satellites-alarms','CCTV / Satellites / Alarms','CCTV, aerials, satellite dishes and alarm installs.','£150 – £3,500',6),
('cleaner','Cleaner','Domestic, end-of-tenancy, deep and commercial cleaning.','£60 – £600',7),
('drainage-specialist','Drainage Specialist','Blockages, CCTV surveys, drain repairs and soakaways.','£90 – £4,000',8),
('driveway-specialist','Driveway Specialist','Block paving, resin, tarmac drives and patios.','£1,200 – £12,000',9),
('electrician','Electrician','Rewires, consumer units, EV chargers and EICR certificates.','£120 – £6,000',10),
('floor-fitter','Floor Fitter','Wood, laminate, LVT, carpet and screed floor fitting.','£250 – £6,000',11),
('gardener','Gardener / Landscape Gardener','Garden design, patios, fencing, turfing and maintenance.','£80 – £15,000',12),
('gas-heating-engineer','Gas / Heating Engineer','Boilers, radiators, gas safety checks and central heating.','£90 – £5,000',13),
('handyman','Handyperson','Odd jobs, flat-pack, shelving, small repairs and fixes.','£60 – £600',14),
('kitchen-specialist','Kitchen Specialist','Kitchen design, supply and full fitting including worktops.','£2,000 – £25,000',15),
('locksmith','Locksmith','Lock changes, emergency entry, uPVC repairs and security upgrades.','£70 – £600',16),
('loft-conversion-specialist','Loft Conversion Specialist','Dormers, hip-to-gable and full loft conversions.','£20,000 – £70,000',17),
('painter-decorator','Painter and Decorator','Interior and exterior decorating, wallpapering and spraying.','£180 – £4,000',18),
('pest-control','Pest Control','Rodents, wasps, bed bugs and proofing treatments.','£80 – £900',19),
('plasterer','Plasterer / Renderer','Skimming, rendering, coving and damp-proof plastering.','£150 – £2,500',20),
('plumber','Plumber','Leaks, boilers, bathrooms and emergency call-outs.','£90 – £3,500',21),
('removals','Removal Services','House and office moves, packing and single-item transport.','£150 – £2,500',22),
('renewables-specialist','Renewables Specialist','Solar PV, batteries, heat pumps and EV charge points.','£1,500 – £20,000',23),
('roofer','Roofer','Repairs, re-roofs, flat roofs, guttering and leadwork.','£150 – £12,000',24),
('security-systems','Security Systems / Alarms','Intruder alarms, access control and monitored security.','£250 – £4,000',25),
('specialist-tradesperson','Specialist Tradesperson','Niche and technical work that does not fit a standard trade.','£150 – £10,000',26),
('stonemason','Stoneworker / Stonemason','Natural stone walls, fireplaces, restoration and carving.','£400 – £20,000',27),
('swimming-pool-specialist','Swimming Pool Specialist','Pool builds, liners, servicing, heating and covers.','£2,000 – £60,000',28),
('tiler','Tiler','Bathrooms, kitchens, floors, wet rooms and natural stone.','£200 – £3,000',29),
('traditional-craftspeople','Traditional Craftspeople','Heritage skills: lime plaster, thatching, timber framing.','£500 – £25,000',30),
('tree-surgeon','Tree Surgeon','Felling, crown reduction, stump grinding and hedge work.','£150 – £3,000',31),
('window-fitter','Window Fitter / Conservatory Installer','Windows, doors, conservatories and glazing repairs.','£400 – £20,000',32)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  blurb = EXCLUDED.blurb,
  typical_cost = EXCLUDED.typical_cost,
  sort_order = EXCLUDED.sort_order;