
INSERT INTO public.trades (slug,name,blurb,typical_cost,sort_order) VALUES
('builder','Builder','Extensions, structural work, conversions and full renovations.','£1,800 – £45,000',1),
('plumber','Plumber','Leaks, boilers, bathrooms and emergency call-outs.','£90 – £3,500',2),
('electrician','Electrician','Rewires, consumer units, EV chargers and EICR certificates.','£120 – £6,000',3),
('painter-decorator','Painter & Decorator','Interior and exterior decorating, wallpapering and spraying.','£180 – £4,000',4),
('carpenter','Carpenter','Fitted joinery, doors, staircases, decking and second fix.','£200 – £8,000',5),
('roofer','Roofer','Repairs, re-roofs, flat roofs, guttering and leadwork.','£150 – £12,000',6),
('plasterer','Plasterer','Skimming, rendering, coving and damp-proof plastering.','£150 – £2,500',7),
('tiler','Tiler','Bathrooms, kitchens, floors, wet rooms and natural stone.','£200 – £3,000',8),
('gardener','Gardener / Landscaper','Garden design, patios, fencing, turfing and maintenance.','£80 – £15,000',9),
('handyman','Handyman','Odd jobs, flat-pack, shelving, small repairs and fixes.','£60 – £600',10);

INSERT INTO public.areas (slug,name,note,sort_order) VALUES
('london','London','All 32 boroughs covered',1),
('manchester','Manchester','Greater Manchester',2),
('birmingham','Birmingham','West Midlands',3),
('bristol','Bristol','Bristol & Bath',4),
('leeds','Leeds','West Yorkshire',5),
('glasgow','Glasgow','Strathclyde',6),
('cardiff','Cardiff','South Wales',7),
('newcastle','Newcastle','Tyne & Wear',8);

INSERT INTO public.pros (id,name,company,trade_slug,area,area_slug,postcode,bio,years,response_mins,day_rate,min_job_budget,availability,services,photo) VALUES
('marcus-webb','Marcus Webb','Webb Plumbing & Heating','plumber','Bristol','bristol','BS1','Family-run heating and plumbing firm covering Bristol and north Somerset. Boiler installs, full bathroom fits and same-day leak work.',18,42,320,90,'immediate',ARRAY['Boiler installation & servicing','Bathroom installation','Leak detection','Emergency call-out'],1),
('priya-shah','Priya Shah','Shah Electrical','electrician','Manchester','manchester','M1','NICEIC-approved contractor specialising in domestic rewires, EV charge points and landlord certification across Greater Manchester.',11,25,300,120,'immediate',ARRAY['Full & partial rewires','EV charger installation','Consumer unit upgrades','EICR reports'],2),
('tom-halloran','Tom Halloran','Halloran Joinery','carpenter','Leeds','leeds','LS1','Bespoke joinery workshop making fitted wardrobes, staircases and alcove units. Twenty-six years on the tools, mostly period property work.',26,90,340,200,'within_month',ARRAY['Fitted wardrobes & alcoves','Staircases','Doors & second fix','Decking'],3),
('dean-okafor','Dean Okafor','Okafor Build Group','builder','London','london','SE15','Extensions, loft conversions and structural alterations across south London. Directly employed team, no subcontracting.',15,65,480,1800,'within_month',ARRAY['Rear & side extensions','Loft conversions','Structural steels','Full renovations'],1),
('sian-roberts','Siân Roberts','Roberts Roofing','roofer','Cardiff','cardiff','CF10','Third-generation roofers covering South Wales. Slate, tile, flat roofs and full leadwork. Free drone survey on re-roofs.',22,55,300,150,'immediate',ARRAY['Re-roofs & slating','Flat roof systems','Gutter & fascia','Leadwork'],2),
('alan-petrie','Alan Petrie','Petrie Decorating','painter-decorator','Glasgow','glasgow','G1','Careful interior decorating and spray finishing for homes and small commercial jobs. Dust-free sanding as standard.',9,35,240,180,'within_week',ARRAY['Interior decorating','Exterior painting','Wallpapering','Spray finishing'],3),
('kirsty-lam','Kirsty Lam','Lam Tiling','tiler','London','london','E8','Precision tiling for bathrooms, wet rooms and kitchens. Large-format porcelain and natural stone a speciality.',8,30,280,200,'within_week',ARRAY['Bathroom & wet room tiling','Kitchen splashbacks','Large-format porcelain','Natural stone'],2),
('greg-mullen','Greg Mullen','Mullen Plastering','plasterer','Birmingham','birmingham','B1','Skimming, rendering and damp-proof plastering across the West Midlands. Clean, quick and tidy.',14,45,230,150,'immediate',ARRAY['Skimming & re-skims','K-Rend rendering','Coving','Damp-proof plastering'],1),
('nadia-hussain','Nadia Hussain','Hussain Gardens','gardener','Manchester','manchester','M20','Garden design and hard landscaping — patios, fencing, turfing and planting schemes. RHS-trained designer.',12,70,260,80,'within_week',ARRAY['Garden design','Patios & paving','Fencing','Turfing & planting'],2),
('bill-carter','Bill Carter','Carter Home Fixes','handyman','Newcastle','newcastle','NE1','Reliable handyman for the jobs nobody else will take. Flat-pack, shelving, small repairs, minor plumbing.',20,20,180,60,'immediate',ARRAY['Flat-pack assembly','Shelving & mounting','Small repairs','Minor plumbing'],3),
('joe-brennan','Joe Brennan','Brennan Plumbing','plumber','London','london','N4','North London plumber for bathrooms, unvented cylinders and boiler swaps. Gas Safe and Unvented registered.',13,38,340,120,'within_week',ARRAY['Boiler swaps','Unvented cylinders','Bathroom installation','Power flushing'],1),
('emma-clyde','Emma Clyde','Clyde Electrical','electrician','Glasgow','glasgow','G41','Domestic and small commercial electrician. Rewires, smart lighting, outdoor power and testing.',7,28,290,120,'within_month',ARRAY['Rewires','Smart lighting','Outdoor power','Periodic testing'],2);

INSERT INTO public.pro_credentials (pro_id,label,kind,verified,verified_at) VALUES
('marcus-webb','ID checked','identity',true,now()),
('marcus-webb','Gas Safe registered','trade_body',true,now()),
('marcus-webb','Public liability £2m','insurance',true,now()),
('priya-shah','ID checked','identity',true,now()),
('priya-shah','NICEIC approved','trade_body',true,now()),
('priya-shah','Public liability £5m','insurance',true,now()),
('tom-halloran','ID checked','identity',true,now()),
('tom-halloran','City & Guilds','qualification',true,now()),
('tom-halloran','Public liability £2m','insurance',true,now()),
('dean-okafor','ID checked','identity',true,now()),
('dean-okafor','FMB member','trade_body',true,now()),
('dean-okafor','Public liability £5m','insurance',true,now()),
('sian-roberts','ID checked','identity',true,now()),
('sian-roberts','CompetentRoofer','trade_body',true,now()),
('sian-roberts','Public liability £2m','insurance',true,now()),
('alan-petrie','ID checked','identity',true,now()),
('alan-petrie','Public liability £1m','insurance',true,now()),
('kirsty-lam','ID checked','identity',true,now()),
('kirsty-lam','TTA member','trade_body',true,now()),
('kirsty-lam','Public liability £2m','insurance',true,now()),
('greg-mullen','ID checked','identity',true,now()),
('greg-mullen','Public liability £2m','insurance',true,now()),
('nadia-hussain','ID checked','identity',true,now()),
('nadia-hussain','RHS qualified','qualification',true,now()),
('nadia-hussain','Public liability £2m','insurance',true,now()),
('bill-carter','ID checked','identity',true,now()),
('bill-carter','Public liability £1m','insurance',true,now()),
('joe-brennan','ID checked','identity',true,now()),
('joe-brennan','Gas Safe registered','trade_body',true,now()),
('joe-brennan','Unvented registered','qualification',true,now()),
('emma-clyde','ID checked','identity',true,now()),
('emma-clyde','SELECT member','trade_body',true,now()),
('emma-clyde','Public liability £2m','insurance',true,now());

INSERT INTO public.reviews (pro_id,author_name,author_place,rating,title,body,job_type) VALUES
('marcus-webb','Hannah D.','Bristol',5,'Bathroom done in four days','Three quotes in under two hours, all with photos of previous work. Picked the middle one and the bathroom was done in four days.','Bathroom refit'),
('marcus-webb','Peter S.','Clevedon',5,'Sorted a leak same day','Rang at 8am with water coming through the ceiling. Marcus was there by eleven and had it capped and repaired by two.','Emergency leak'),
('marcus-webb','Louise K.','Bristol',4,'Good boiler install','Tidy boiler swap, explained the controls properly. Took half a day longer than quoted but no extra charge.','Boiler installation'),
('priya-shah','Ade O.','Manchester',5,'Actually turned up','I had been ghosted by two electricians before this. Priya turned up when she said she would, which is all I wanted.','Consumer unit upgrade'),
('priya-shah','Marianne T.','Stockport',5,'EV charger, no fuss','Quoted on a video call, installed a week later, handled the DNO paperwork herself.','EV charger installation'),
('tom-halloran','Ruth M.','Leeds',5,'Beautiful wardrobes','Being able to read real reviews rather than a star rating with no detail made the difference. No haggling, no hard sell.','Fitted wardrobes'),
('tom-halloran','David B.','Harrogate',4,'Lovely staircase work','Genuine craftsmanship on a Victorian staircase. Slow to reply at first but worth waiting for.','Staircase repair'),
('dean-okafor','Femi A.','London',5,'Extension on time','Six-week rear extension finished on the day he said it would be. Weekly written updates.','Rear extension'),
('dean-okafor','Clare W.','London',4,'Solid loft conversion','Good work and clean site. Some back and forth on the final invoice but resolved fairly.','Loft conversion'),
('sian-roberts','Gareth P.','Cardiff',5,'Drone survey was a nice touch','Showed me photos of the actual damage before quoting. Re-roofed in three days.','Re-roof'),
('alan-petrie','Morag F.','Glasgow',5,'Immaculate finish','Two rooms and a hallway, not a single spot of paint anywhere it should not be.','Interior decorating'),
('kirsty-lam','Ben J.','London',5,'Wet room is perfect','Large-format porcelain, dead level, grout lines you could set a watch by.','Wet room tiling'),
('greg-mullen','Aisha R.','Birmingham',5,'Fast and clean','Whole ceiling skimmed and cleaned up in a day.','Ceiling skim'),
('nadia-hussain','Tom E.','Manchester',4,'Great garden design','Design was lovely. Planting took a fortnight longer than planned due to weather.','Garden design'),
('bill-carter','Sue H.','Newcastle',5,'Nothing was too small','Put up six shelves, fixed a door and rehung a gate. Charged less than quoted.','Odd jobs'),
('joe-brennan','Nikhil G.','London',5,'Unvented cylinder swap','Explained the options honestly instead of upselling. Great work.','Cylinder replacement'),
('emma-clyde','Fiona M.','Glasgow',4,'Smart lighting sorted','Set up the whole downstairs on smart switches and left it working properly.','Smart lighting');
